### ISSUE TITLE
Import this mod to Fabric 1.19.2

### ISSUE THREAD

**Issue by pdfmarkov** [misigno/createdpcompat-1.20.X#1]
Hi! I haven't found any other ways to contact you, so the question is: can you please make a version for 1.19.2 Fabric. I hope it's not too hard, but you would have saved me heh. Thanks!

**Comment by misigno** [comment]
I made a quick edit to backport to 1.19.2 make sure you use datapackportals 1.2.2. Don't have time to test it now so it's only available as a Release on Github. Do come back here if you encounter issues
